    version: 2.1
    executors:
      docker-publisher:
        environment:
          IMAGE_NAME: wesleycharlesblake/devops-tools
        docker:
          - image: circleci/buildpack-deps:stretch
    jobs:
      build:
        executor: docker-publisher
        steps:
          - checkout
          - setup_remote_docker
          - run:
              name: Build Docker image
              command: |
                TAG="0.1.${CIRCLE_BUILD_NUM}"
                docker build -t "${IMAGE_NAME}":"${TAG}" -t "${IMAGE_NAME}":"latest" .
          - run:
              name: Publish Docker Image to Docker Hub
              command: |
                docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
                docker push ${IMAGE_NAME}:${TAG}
    workflows:
      version: 2
      build:
        jobs:
          - build:
              filters:
                branches:
                  only: master