version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trust

    steps:
      - checkout
      - run:
          name: Build and push Docker image
          command: |
            TAG="0.1.${CIRCLE_BUILD_NUM}"
            docker build -t wesleycharlesblake/devops-tools:$TAG .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push wesleycharlesblake/devops-tools:$TAG